错误：
    error
    ReferenceError 引用错误。引用的变量不存在
    TypeError 数据类型不正确的错误
    RangeError 数据值不在其允许范围内 Maxinum call stack size exceeded
    SyntaxError 语法错误

处理错误：
    捕获错误：try {}  cach（error）{} 这里的error是错误类型，（error的属性：error.message，error.stack
    抛出错误：throw new Error('')
